version: "3.3"

services:
  horizon: 
    image: yanyao/horizon:master
    ports:
      - 80:80
    networks:
      - mgmt
    environment:
      INIT_DB: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
   

networks:
  mgmt:
    external:
      name: mgmt
